[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "BlinkswagDashboard"
authors = [{name = "Blinkswag", email = "swag@blinkswag.com"}]
dynamic = ["version", "description"]
